# Generated by Django 5.2.7 on 2025-10-30 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0004_rename_module_task_module'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sheet',
            old_name='descreption',
            new_name='description',
        ),
    ]
