# Generated by Django 5.2.7 on 2025-10-21 05:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0002_project_module_task_delete_timesheetentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.DecimalField(decimal_places=2, max_digits=4)),
                ('descreption', models.TextField(blank=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timesheets.module')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timesheets.project')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timesheets.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
