# Generated by Django 5.2.7 on 2025-10-31 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_app', '0003_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='text',
        ),
        migrations.AddField(
            model_name='comment',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
