# Generated by Django 5.2.7 on 2025-11-01 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article_app', '0004_remove_comment_text_comment_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
