# Generated by Django 5.1.2 on 2025-10-29 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0003_sheet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='Module',
            new_name='module',
        ),
    ]
